development:
  adapter: postgresql
  encoding: utf8
  database: missed
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  encoding: utf8
  database: missed
  pool: 5
  timeout: 5000

production:
   url: <%= ENV['HEROKU_POSTGRESQL_TEAL_URL'] %>
